parameters:
  dataset: trec
  result_path: 'neural_cls/results/'
  usemodel: CNN
  worddim: 300
  pretrnd: wordvectors/mts_dataset_300.vec
  reload: 0
  checkpoint: "."
  initdata: 2
  acquiremethod: mnlp